-- ************************************************************
-- *** Creación del Tablespace del esquema de Data Warehouse de ValET***
-- ************************************************************

CREATE TABLESPACE "VALET_STATISTICS_DW_TS" 
	DATAFILE 'RUTA_ALMACENAMIENTO_ESQUEMA/VALET_STATISTICS_DW_TS_000001.ora' SIZE 32M AUTOEXTEND ON;

-- ****************************** TABLESPACE PARA LOS ÍNDICES **********************************	

CREATE TABLESPACE VALET_STATISTICS_DW_INDEX_TS DATAFILE 'RUTA_ALMACENAMIENTO_ESQUEMA/VALET_STATISTICS_DW_INDEX_TS_000001.ora' SIZE 32M AUTOEXTEND ON;

-- ****************************** USUARIO PROPIETARIO **********************************
CREATE USER "VALET_STATISTICSDWOWNER"  PROFILE "DEFAULT"
	IDENTIFIED BY "XXXXX" DEFAULT TABLESPACE "VALET_STATISTICS_DW_TS"
		ACCOUNT UNLOCK;

GRANT ALTER ANY TABLE TO "VALET_STATISTICSDWOWNER";
GRANT CREATE ANY TABLE TO "VALET_STATISTICSDWOWNER";
GRANT DROP ANY TABLE TO "VALET_STATISTICSDWOWNER";
GRANT "RESOURCE" TO "VALET_STATISTICSDWOWNER";
GRANT "CONNECT" TO "VALET_STATISTICSDWOWNER";

COMMIT;
