-- ************************************************************
-- *** Creación del Tablespace del esquema de Configuración ***
-- ************************************************************

-- ****************** TABLESPACE PARA EL MODULO DE CONFIGURACIÓN *****************
CREATE TABLESPACE "VALET_CONFIGURACION_TABLESPACE" 
	DATAFILE 'RUTA_ALMACENAMIENTO_ESQUEMA/CONFIGURACION_TABLESPACE_000001.ora' SIZE 128M AUTOEXTEND ON;

-- ****************************** USUARIO PROPIETARIO **********************************
CREATE USER "VALET_CONFIGOWNER"  PROFILE "DEFAULT"
	IDENTIFIED BY "XXXXX" DEFAULT TABLESPACE "VALET_CONFIGURACION_TABLESPACE"
		ACCOUNT UNLOCK;

GRANT ALTER ANY TABLE TO "VALET_CONFIGOWNER";
GRANT CREATE ANY TABLE TO "VALET_CONFIGOWNER";
GRANT DROP ANY TABLE TO "VALET_CONFIGOWNER";
GRANT "RESOURCE" TO "VALET_CONFIGOWNER";
GRANT "CONNECT" TO "VALET_CONFIGOWNER";

COMMIT;
