-- ********************************************************
-- ************** Creación de sinónimos *******************
-- ********************************************************

CREATE SYNONYM "USER_VALET" FOR "VALET_CONFIGOWNER"."USER_VALET";
CREATE SYNONYM "TSL_VALET" FOR "VALET_CONFIGOWNER"."TSL_VALET";
CREATE SYNONYM "TSL_COUNTRY_REGION" FOR "VALET_CONFIGOWNER"."TSL_COUNTRY_REGION";
CREATE SYNONYM "C_TSL_IMPL" FOR "VALET_CONFIGOWNER"."C_TSL_IMPL";
CREATE SYNONYM "TSL_COUNTRY_REGION_MAPPING" FOR "VALET_CONFIGOWNER"."TSL_COUNTRY_REGION_MAPPING";
CREATE SYNONYM "KEYSTORE" FOR "VALET_CONFIGOWNER"."KEYSTORE";
CREATE SYNONYM "SYSTEM_CERTIFICATE" FOR "VALET_CONFIGOWNER"."SYSTEM_CERTIFICATE";
CREATE SYNONYM "C_STATUS_CERTIFICATE" FOR "VALET_CONFIGOWNER"."C_STATUS_CERTIFICATE";

CREATE OR REPLACE SYNONYM "SQ_USER_VALET" FOR "VALET_CONFIGOWNER"."SQ_USER_VALET";
CREATE OR REPLACE SYNONYM "SQ_TSL_VALET" FOR "VALET_CONFIGOWNER"."SQ_TSL_VALET";
CREATE OR REPLACE SYNONYM "SQ_TSL_COUNTRY_REGION" FOR "VALET_CONFIGOWNER"."SQ_TSL_COUNTRY_REGION";
CREATE OR REPLACE SYNONYM "SQ_C_TSL_IMPL" FOR "VALET_CONFIGOWNER"."SQ_C_TSL_IMPL";
CREATE OR REPLACE SYNONYM "SQ_TSL_COUNTRY_REGION_MAPPING" FOR "VALET_CONFIGOWNER"."SQ_TSL_COUNTRY_REGION_MAPPING";
CREATE OR REPLACE SYNONYM "SQ_SYSTEM_CERTIFICATE" FOR "VALET_CONFIGOWNER"."SQ_SYSTEM_CERTIFICATE";
